scoopapa/DH

data/mods/perfectgalar/pokedex.js
data/mods/perfectgalar/scripts.js

Didn't do the pikachu incompatibility stuff yet

Perfect Galar stuff

---

data/mods/crossoverchaos/moves.js

Trash Compaction is Wall-E's ability, it does that stuff, it also helps so they may be updated accordingly whenever other abilities like that pop up

Customizing hazards so Trash Compaction ignores such

---

config/formats.js
data/mods/crossoverchaos/abilities.js
data/mods/crossoverchaos/learnsets.js
data/mods/crossoverchaos/moves.js

wildly ooc this fanfic is terrible

hey look i did a thing that isn't crossover chaos for a bit

---

data/mods/fealpha/formats-data.js
data/mods/fealpha/pokedex.js

Credits to Scoopapa for the Tool

Add FE Alpha Data

---

config/formats.js
data/mods/twisted/scripts.ts
data/mods/twisted/statuses.ts

let me know when it's ready to be tested :)

Add Twisted Pokémon to mods and formats

---

data/mods/roseredirisblue/scripts.js
data/mods/roseredirisblue/statuses.js

I aligned the statuses.js and scripts.js files with the code structure that DH follows. I'm sorry for being annoying with all these commits lately, but I fixed everything myself and all that's left is to click the commit button <3

rrib fixed statuses and scripts files

---

data/mods/roulettemons/pokedex.js

Update pokedex.js (gen 7 roulettemons)

---

data/mods/roulettemons/learnsets.js

Update learnsets.js (gen 7 roulettemons)

---

config/formats.ts
data/mods/sylvemonstest/scripts.ts

Fix SylveMons crashing upon attempting Mega Evolution

Update scripts.ts (sylvemonstest)

---

data/mods/sylvemonstest/conditions.ts

turns out i can get rid of the 'none ended' messages and i am just an idiot

sylvemons weather fix episode 2

---

config/formats.ts
data/mods/m4av6/formats-data.ts
data/mods/roulettemons/random-teams.ts

I dunno why Chillyte has this problem but I can't seem to fix it myself
Otherwise this should be working

[Roulettemons Randbats] Z-Moves

---

config/formats.ts
data/mods/mnm4a/abilities.ts
data/mods/mnm4a/scripts.ts

I can't believe this actually works (and won't even require constant maintenance)

hi I made mnm4a on a whim

---

config/formats.ts
data/mods/m4av6/abilities.ts
data/mods/m4av6/moves.ts

heck yes they all passed can't wait for Mega Bastiodon meta
tested earlier so I could be ready C:

[Gen 8 Megas for All] Balance Changes Poll Results

---

data/mods/pkmnyb/scripts.ts

the file after the move additions is c/p'd from sylvemons for now until i can figure out exactly what to do

trying to make pkmn yb playable part 2

---

data/mods/m4av6/abilities.ts
data/mods/m4av6/moves.ts

Affected: Showdown, Tempestuous, Nightmare Heart, Alchemist

[Gen 8 Megas for All] Minor Polish

---

data/mods/megarevolution/pokedex.ts

Fixed lordiathan (rega rev/pokedex.ts)

---

config/formats.ts
data/mods/fealpha/rulesets.ts
data/mods/feuu/rulesets.ts
data/mods/sylvemonstest/rulesets.ts

Adding Data Mod to FEA/FEUU/Sylve!

---

data/mods/tothegigantamax/formats-data.ts

Forgot to update TTG formats-data

---

data/mods/tothegigantamax/moves.ts
data/mods/tothegigantamax/pokedex.ts

Activating and adding moves for Darmanitan-G, Rapidash-G, Incineroar, Decidueye, Scizor, Slowbro-G, Reshriam, Flygon, Glaceon, Skuntank, and Giratina
I'm fairly confident that they all should work properly but I'm worried about Incineroar, Reshiram, Flygon, and Glaceon

TTG More GMax Forms

---

config/formats.ts

In a new PR, because for some reason it's correct on the branch i did all my editing on but it didnt merge ???

Fix FEUU format

---

data/mods/m4av6/pokedex.ts

I can't believe I did that to Cinccino

---

data/mods/feuu/abilities.ts

Ceiling is the worst word to spell and I really dont like it

Made a typo in the most recent FEUU update

---

config/formats.ts
data/mods/m4asandbox/formats-data.ts
data/mods/m4asandbox/rulesets.ts
data/mods/m4av6/abilities.ts
data/mods/m4av6/conditions.ts
data/mods/m4av6/scripts.ts

(this is not really important there's no rush
just if you happen to be on before the next time I have to make an actual PR)

Megas for All: Minor corrections

---

config/formats.ts
data/mods/conniecorddraft/learnsets.ts

I have some other stuff I wanted to add to this, but I'm gonna have to hold off until github desktop realizes I made a new branch and lets me load it

Minor updates

---

data/mods/m4av6/abilities.ts

It causes a crash currently I'm so sorry ;-;

Megas for All: Major Implode bugfix

---

data/mods/m4av6/abilities.ts
data/mods/m4av6/conditions.ts
data/mods/m4av6/moves.ts
data/mods/m4av6/rulesets.ts
data/mods/m4av6/scripts.ts

M4A: Silvally but it actually works

---

data/mods/m4asandierbox/abilities.ts

Ability Set #3

---

data/mods/pokemonns/pokedex.ts

Pokemon N&S quickfix

---

config/formats.ts
data/mods/blindsided/abilities.ts

Super happy to have helped Magmajudis with the main format : D
This took like a minute to set up I was excited when Low-Key suggested it

Blindsided VGC by request

---

data/mods/pupumons/learnsets.ts
data/mods/pupumons/moves.ts
data/mods/pupumons/pokedex.ts

some moveset and vgc related updates

Pupumons Quickpatch

---

data/mods/earthsky/pokedex.ts

Fix Beedive's ability name [Ready to merge]

---

config/usergroups.csv

Make inkbug's promotion permanent

---

data/mods/evolutionproject/formats-data.ts
data/mods/evolutionproject/items.ts
data/mods/evolutionproject/pokedex.ts

Helps to have so many eyes on this all of the sudden O:
I left out Lediluck by mistake! and also, Alchemissus was so gluttonous that they could no longer levitate, oops

Evolution Project minor fixes

---

data/mods/gen8outheorymon/pokedex.ts
data/mods/gen8outheorymon/scripts.ts

Revert "Update pokedex.ts"

---

config/formats.ts
data/mods/outheorymons/pokedex.ts
data/mods/outheorymons/scripts.ts

I have made a new folder outheorymons with the files needed.

Changed OU Theorymons' mod folder

---

data/mods/branchedpotential/formats-data.ts
data/mods/branchedpotential/pokedex.ts
data/mods/branchedpotential/scripts.ts
data/mods/paleomons/learnsets.ts
data/mods/paleomons/pokedex.ts

- Gave Cradily Grass/Ground + Recover
- Removed Shell Smash from Omastar
- Removed High Horsepower from Mamoswine
- Made Icicle Crash Mamoswine non-event exclusive
- Fixed spelling error (Wizmagius -> Wizmagis)

Paleomons + Branched Potential Minor Fixes

---

data/mods/outheorymons/formats-data.ts
data/mods/outheorymons/items.ts
data/mods/outheorymons/pokedex.ts
data/mods/outheorymons/scripts.ts

- New slates implemented (Dragon/Steel Haxorus, Slack Off Guzzlord, Dragon/Fairy Moonblast Latias, Bug/Ground Scolipede, Rapid Spin Kommo-o, and +10 Spe Dual Wingbeat Gyarados)
- Updates to tiering based on recent VR updates.

Updates to OU Theorymons

---

config/formats.ts
data/mods/undertheweather/formats-data.ts

added a new solomod, only weather related pokemon are allowed.

Under The Weather

---

data/mods/paleomons/formats-data.ts
data/mods/paleomons/learnsets.ts
data/mods/paleomons/pokedex.ts

Just temporary bc I want to check its actually Shellos/Gastrodon's fault Paleomon's teambuilder is funky. I'm 90% sure its their fault but just in case y'know?

Paleomons - While you're merging Viz's fix can you also merge this commit that deletes Gastrodon-Entity? Thank you

---

config/formats.ts

I mean I hope it fixes it? I can't see it breaking anything so let's hope so lol

Teambuilder Fix for PaLCeomons

---

data/mods/outheorymons/pokedex.ts
data/mods/outheorymons/scripts.ts

Newest Slate Update for Theorymons

New Slate for OU Theorymons

---

data/mods/paleomons/learnsets.ts

Comedy has officially left Paleomons

Paleomons Learnset Changes

---

config/formats.ts
data/mods/paleomons/abilities.ts
data/mods/paleomons/moves.ts
data/mods/paleomons/scripts.ts

- Fixed Persistence not activating with immunities
- (Hopefully) Fixed PaLCeomon's teambuilder (ty Viz for telling me how to do this x)
- Minor learnset and stat changes (removed Spikes from Omastar, Dreepy and Drakloak had the same stats?? so now Dreepy has been heavily nerfed lol)
- Added animations for all custom moves (again, ty Viz for telling me how to do this x)
- Also removed some debugging messages I somehow forgot to delete last pr lol

Paleomons Bug Fixes + Other Misc Stuff

---

config/formats.ts
data/mods/earthsky/abilities.ts
data/mods/earthsky/items.ts
data/mods/earthsky/moves.ts
data/mods/earthsky/pokedex.ts
data/mods/earthsky/scripts.ts

My last edits didn't actually work, but I decided to add a bunch of other stuff, so it's fiiiine!

Earth & Sky 1.3

---

config/formats.ts
data/mods/boatmod/formats-data.ts
data/mods/pupumons/formats-data.ts
data/mods/pupumons/scripts.ts

mostly for the national dex formatting

Teambuilder Fixes for Pupumons and Boatmod

---

data/mods/feuu/pokedex.ts
data/mods/paleomons/abilities.ts
data/mods/paleomons/learnsets.ts
data/mods/paleomons/moves.ts
data/mods/paleomons/pokedex.ts
data/mods/paleomons/scripts.ts

- Gave Minun Electric/Steel instead of Electric/Normal (lol)
- Added Photon Ball (lol x2)
- Reworked Persistence; fixed bug where Persistence doesn't trigger on Pokemon with immunity abilities

Paleomons Bug Fixes

---

data/mods/paleomons/pokedex.ts

Shoutouts to Me for giving Anklarmor 11 special defence.

Paleomons Minor Fix (Singular)

---

data/mods/eternalpokemonv2/formats-data.ts
logs/errors.txt

Eternal pokemon v2

---

config/formats.ts
data/mods/outheorymons/formats-data.ts
data/mods/outheorymons/pokedex.ts
data/mods/outheorymons/random-teams.ts
data/mods/outheorymons/scripts.ts

Revert "Theorymons Huge Update + Slate "

---

data/mods/gen1expansionpack/learnsets.ts

KEP: Rapidash-Galar should have Hyper Beam

---

data/mods/gen2crystalseviiislands/conditions.ts
data/mods/gen2crystalseviiislands/moves.ts
data/mods/gen2crystalseviiislands/scripts.ts

Fixed a couple of moves that weren't working properly.
we're an up-to-date pet mod now, hooray!

Gen2csi: bug fixes

---

data/mods/gen2crystalseviiislands/moves.ts

- Added code comment to Parry warning not to mindlessly port it to a double battle format (cuz it'll almost certainly not work as intended)
- Added a volatile tag to Malnourish in-battle

Sevii Islands Tweaks

---

data/mods/svspeculative/moves.ts
data/mods/svspeculative/scripts.ts

SV proto: add Tera move and fix Ability issue

---

data/mods/gen3hoennification/formats-data.ts

See [this post](https://www.smogon.com/forums/threads/solomods-megathread.3660004/page-8#post-9300524) for the new bans/unbans.

Update formats-data.ts (Hoennification)

---

config/formats.ts
data/mods/gen2crystalseviiislands/moves.ts
data/mods/gen5/rulesets.ts
data/mods/gen5derivativeunova/formats-data.ts
data/mods/gen5derivativeunova/rulesets.ts
data/mods/gen5derivativeunova/scripts.ts

Adding Paulluxx's Pet Mod to DH as he's ready to start it up.
Also committing a fix for Parry in C:SI where it would succeed even if the foe's attack missed.

Gen 5: Derivative Unova 

---

config/formats.ts
data/mods/m4akalos/formats-data.ts
data/mods/svspeculative/formats-data.ts
data/mods/svspeculative/items.ts
data/mods/svspeculative/moves.ts
data/mods/svspeculative/scripts.ts

SVspec teambuilder support

---

config/formats.ts

Oof, I did this when trying to fix Sawsbuck and wasn't paying close enough attention to fix it!

Fix M4A formats

---

data/mods/legendshoopa/abilities.ts
data/mods/legendshoopa/conditions.ts
data/mods/legendshoopa/formats-data.ts
data/mods/legendshoopa/moves.ts

Anl Bug Fixes x

---

data/mods/svspeculative/scripts.ts

I am so sorry
I had no idea this was even possible because the change was localized to the mod folder
It seems like it's because this.dataCache is global and I didn't realize

Correct accidental sitewide movepool change o_o

---

data/mods/gen1kantoification/pokedex.ts

So during the Mega nerf process, I forgot to account for Mega X and Y formes, so yeah, this fixes that.

Kantoification - Update Mega X and Y Stats

---

data/mods/gen1kantoification/formats-data.ts
data/mods/gen1kantoification/learnsets.ts
data/mods/gen1kantoification/pokedex.ts

Send the obviously broken mons to Uber, fix eventOnly, and fix Steel/Dark/Fairy KEP mons.

Minor Fixes (Kantoification)

---

data/mods/bustamove/moves.ts
data/mods/bustamove/scripts.ts

For Ember, Vine Whip, and Water Gun
I sleep now.

Bust A Move Slate 35

---

data/mods/legendshoopa/pokedex.ts

Abyssylar is going as Cornutropia for Halloween

Legends: Hoopa bugfix

---

data/mods/earthsky/abilities.ts
data/mods/earthsky/items.ts
data/mods/earthsky/moves.ts
data/mods/earthsky/pokedex.ts
data/mods/earthsky/scripts.ts

This should be the last update before Gen IX
Now with rebasing so there aren't any problems (I hope)

Earth & Sky update

---

data/mods/kaensdex/pokedex.ts

Spavader wasn't receiving moves from its pre-evolution.

KaensDex bug fixing a fakemon

---

data/mods/svspeculative/scripts.ts

Holy heck my computer hates Github so much lately
Why did it take an entire hour to test two iterations of such a tiny change @.@

Terastal but with more STABs

---

config/formats.ts
data/mods/gen3sampleteamrandbats/random-teams.ts

Thanks to Inkbug for linking the code from M4A Sandbox to help me figure this out!

[Gen 3] OU Sample Team Randbats: Print the name of the team on only the user's side

---

config/formats.ts
data/mods/bookofenigmas/conditions.ts
data/mods/bookofenigmas/formats-data.ts
data/mods/bookofenigmas/scripts.ts

- Some movepool additions and missing mons added, nothing too crazy
- I'm also changing the mod from a [gen 9] one to a [gen 8] one. I doubt this is the reason why the learnset is so funky, but its worth a shot

Book of Enigmas Minor Fixes

---

data/mods/metamons/pokedex.ts

metamons patch

---

data/mods/bustamove/moves.ts
data/mods/bustamove/scripts.ts

Revert "Bust a Move Slate 36"

---

data/mods/gen3hoenngaiden/formats-data.ts

Didn't properly remove Kleavor from the mod whoops!

Hoenn Gaiden: remove kleavor

---

config/formats.ts
data/mods/gen1glitch/formats-data.ts
data/mods/gen1glitch/pokedex.ts
data/mods/gen1glitch/scripts.ts

Ban all glitch mons >= 650 BST, and add Data Mod

[Gen 1] Glitch

---

config/formats.ts

Banning Wrap. The new Pet Mod team tour will have [Gen 1] Glitch as the fifth format. I want to make sure everything is ready

[Gen 1] Glitch OU

---

data/mods/m4akalos/abilities.ts
data/mods/m4akalos/conditions.ts
data/mods/m4akalos/items.ts
data/mods/m4akalos/moves.ts
data/mods/m4akalos/pokedex.ts

Just copy-pasting in some old Megas!

M4A Slate 5.5
