data/mods/sylvemonstest/abilities.ts, data/mods/sylvemonstest/items.ts, data/mods/sylvemonstest/moves.ts, data/mods/sylvemonstest/statuses.ts
Includes fixes for Inverse Room, Reverse Core, Mind Trick, Safety Socks, Shield Slam, Quick Feet, RageCandyBar, Dark Rising and Cursed Body
(Safety Socks and Shield Slam don't really count because I just copied from the Gen VIII effects that match them, but I helped with the rest, at least XP)
=> [Sylvemons] Bugfixes

data/mods/sylvemonstest/abilities.ts, data/mods/sylvemonstest/conditions.ts, data/mods/sylvemonstest/moves.ts, data/mods/sylvemonstest/scripts.ts
**Bugfixes:** 
- Fixed Air Current and Shadow Sky not visually deactivating properly
- Fixed some activation messages to do with Air Current and Shadow Sky
- Fixed bug where Stamina-adjacent abilities counted Synthesis-adjacent moves as "damaging hits" for some reason 
- Fixed Body Press not calculating correctly (I think... the calc actually seems a bit off, uhm, I might need a second opinion on this one...? Either way it should be calculating the same as Shield Slam now at least!) 
**Additions:**
- Added code for the ability Time Warp, copied from Hematite's code for it from Smash Mods Melee
=> SylveMons bugfixes variety hour

config/formats.ts, data/mods/sylvemonstest/conditions.ts, data/mods/sylvemonstest/scripts.ts
the line "mod: 'm4av6'," got deleted from the mega spooky cup format on accident when hema was updating our formats with the qol mega thing
edit 12:34 pm: turns out i fixed Air Current in sylvemons incorrectly in my last patch so i have now amended that as well (big oops)
edit 1:22 pm: fix crash in sylvemons scripts.ts
=> Update formats.ts (& sylvemonstest conditions.ts)

data/mods/genx/learnsets.ts, data/mods/genx/pokedex.ts
Adding evoLevels because I *think* LCs and NFEs need them to let them use Eviolite
=> [Gen X] adding evoLevels + fix for teambuilder crash (i think) + a movepool fix 

config/formats.ts
Crowned was previously unconditionally banned, which appears to be not as intended. I fixed it but probably not in the most elegant way, since I'm not particularly familiar with how BH formats are supposed to work; everything in the format _looked_ like it should be working and wasn't so I just bypassed it.
Crowned is banned from holding any non-Rusted Sword item, its ability cannot be changed from Intrepid Sword, and no Pokemon aside from it can use that ability. It also works for base Zacian holding Rusted Sword I think. 
Once again idk if this isn't how BH is supposed to work because I don't know jack about BH but it should at least be functional.
=> NDBH Zacian-Crowned fix

data/mods/gen2crystalseviiislands/moves.ts
While testing CSI, we found out that Substitute is working incorrectly for Gen 2 OU (and probably all Gen 2 based formats) on DH.
Essentially on DH:
- Spikes failed when used on a Substitute
- Swagger failed when used on a Substitute (In Gen 2, Swagger partially bypasses Substitute - It just doesn't inflict the confusion status)
_*These moves work correctly on base Pokemon Showdown_.
=> Crystal Sevii Islands - Gen 2 Substitute Bug

data/mods/cleanslate/pokedex.ts
The teambuilder was incorrectly saying that a good handful of Pokemon were able to learn moves that they actually weren't. This issue wasn't present in either CSM or CS2, and I pinned it down to "prevos aren't being marked as null, so the teambuilder is carrying over those learnset items when they shouldn't" (which was the only difference I could find between the code of this and CSM). This should fix it; the only thing I'm uncertain about is whether marking the prevo as null for Lycanroc-Midnight will actually do anything, but hopefully it does lol.
=> Teambuilder fix for Gen 7 Clean Slate

data/mods/outheorymons/pokedex.ts, data/mods/outheorymons/scripts.ts
- Adding +20 SpD and Morning Sun to Golisopod
- Adding Competitive to Raikou
- Reordering pokedex.ts to the usual Pokedex order
- Zarude now has Tough Claws as Hidden Ability instead of second ability, for consistency
- Zarude-Dada now has Zarude's changes (it definitely doesn't inherit them automatically, I checked)
=> Updates to OU Theorymons

data/mods/outheorymons/pokedex.ts, data/mods/outheorymons/scripts.ts
- Obstagoon receives +10 Speed
- Mudsdale receives +10 Defense and Shore Up.
=> Updated OU Theorymons

config/formats.ts, data/mods/earthsky/scripts.ts, data/mods/gen2doubles/moves.ts, data/mods/gen2doubles/scripts.ts, sim/battle.ts, sim/field.ts
Gen 2 Doubles: Implementing spread damage reduction and screen protection variance
Earth & Sky: Removing global battle.ts and field.ts edits (I tested this BOTH IN E&S AND IN REGULAR FORMATS and it doesn't crash) as they now work within the mod
=> Gen 2 Doubles and Earth & Sky

data/mods/gen1expansionpack/moves.ts, data/mods/gen1expansionpack/typechart.ts
Metal Sound and Flash Cannon drop SpD, but for Special to be dropped in the Gen 1 sim, both SpA and SpD must be considered. ausma did not know this when programming the moves, which is why Fake Tears didn't work either.
Dark was 0.5x vs Psychic for some reason and it took _checks notes_ a week or two for it to get noticed.
=> Gen 1 KEP: Fix Metal Sound, Flash Cannon, and Dark VS Psychic

data/mods/abilitypos/formats-data.ts, data/mods/impv2/formats-data.ts
Created a formats-data.ts file for abilitypos and added mons from new impersonators slate into the formats-data.ts file.
=> Teambuilder fix for abilitypos and impersonators

data/mods/gen1/moves.ts, data/mods/gen2/moves.ts, data/mods/gen2crystalseviiislands/moves.ts, data/mods/gen3/moves.ts, data/mods/gen4/moves.ts, data/mods/gen5/moves.ts, sim/global-types.ts
This should patch every move in gens 1, 2, 3, 4, 5 and mods based on them to work as intended. A lot of moves were misusing a field name of 'effect' where it should have been labelled 'condition' and this caused them to not apply the new functionality for the tiers based upon that generation.
Haven't deleted any code to achieve this so nothing should be at risk of breaking. The interface code added to globals-types is a slightly modified snippet from globals.ts on smogon/pokemon-showdown , commit hash 62e433d5352e3ae495b1e52ac9645dd7b29a063e
It isn't currently used but I believe in the future it should be useful for creating new custom move effects for our pet mods.
=> Fix gens 1-5 moves condition lookup

data/mods/gen1/moves.ts, data/mods/gen1expansionpack/moves.ts
Counter in Gen 1 is supposed to double the damage of the final hit from multihit moves but was seemingly doubling the entire attack. Ported the function that the main PS server uses to fix.
KEP has redundant code for the move Counter, so I've removed that as well
=> gen1: fix counter damage for multihit moves

data/mods/gen2crystalseviiislands/moves.ts, sim/dex.ts
Sevii Islands will have its own Hidden Power type subfunction in dex.ts as it's the only place to really add it.
Hidden Power Cosmic is generated by creating a subpattern of types off of an even-numbered Speed DV. Hidden Power Fighting is procedurally 'knocked-off' of this DV pattern and all Hidden Power types are bumped along the chain one stage essentially. Odd-numbered Speed DVs do not change the Hidden Power type and remain identical to base Gen 2, meaning that a perfect Speed DV (fifteen) will not change the Hidden Power type of a Pokemon.
=> C:SI Hidden Power Cosmic

data/mods/gen5derivativeunova/formats-data.ts, data/mods/gen5derivativeunova/scripts.ts
Accidentally had Torn-T listed as Lando-T, fixing~
=> Derivative Unova: Unbanning Tornadus-T

data/mods/gen3hoenngaiden/pokedex.ts
Camerupt's BST was meant to be reverted alongside the other changes recently
=> Hoenn Gaiden: Missed Out Change

config/formats.ts, data/mods/m4asandbox/moves.ts, data/mods/svspeculative/abilities.ts, data/mods/svspeculative/formats-data.ts, data/mods/svspeculative/moves.ts, data/mods/svspeculative/scripts.ts
Adds the new content from the latest trailer (Anger Shell, Armor Cannon and Bitter Blade), but also attempts to make the teambuilder exclude certain transfer-only moves so that it more realistically represents the format!
The format still follows Custom Game rules and every move is legal, but the learnsets displayed in the teambuilder should now be more limited, which gives useful information.
=> SVspec update!

data/mods/bustamove/moves.ts, data/mods/bustamove/scripts.ts
With Okis' permission, I've taken on coding what I can for this mod.
Newly altered moves include: Acupressure, Aerial Ace, Avalanche, Bone Rush, Brick Break, Comet Punch (Secondary Effect originally missing), Disarming Voice, Drill Peck, Eerie Impulse, Extrasensory, False Surrender, Flame Wheel, Flower Shield, Guillotine, Hyperspace Hole, Inferno, Iron Tail, Leaf Tornado, Life Dew, Magnetic Flux, Magnitude (and by extent, this slightly alters Grassy Terrain), Misty Explosion, Night Daze, Nightmare, Petal Dance, Poison Tail, Rock Wrecker, Scary Face, Shadow Force, Sheer Cold, Spark, Sparkling Aria, Tar Shot, Triple Kick, Trump Card, Twister, and Zap Cannon.
=> Bust a Move Backlog Clearing

data/mods/gen1johtomons/formats-data.ts
turns out more mons were actually missing
=> Update formats-data.ts for Johtmons

data/mods/gen1expansionpack/formats-data.ts, data/mods/gen1expansionpack/moves.ts
I forgor :skull:
So when I was force-pushing the SV update I literally just forgot to manually add the new moves. They should at least function now.
Scream Tail and Toedscruel proved to be overbearing in their debut to the metagame, and have thus been banned for the initial tournament. Given that, I'm just sending them to Ubers now, to prevent confusion among new players.
For the sake of transparency and giving people somewhere to look for reasoning, I'll use this space to post.
Scream Tail is one of the bulkiest Pokemon in the game, it's kind of disgusting. This, coupled with unparalleled coverage, means it can get away with murder. It viably runs Rest against even Snorlax and Tauros assaults, which is usually a sign of a problem; it takes less damage from Tauros than a Seismic Toss. …
=> KEP: Fix new moves, ban Scream Tail & Toedscruel
